name: Automated tests for client and server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build Server
      run: g++ -pthread -o server server.cpp

    - name: Build Client
      run: g++ -o client lab6-linux-client.cpp

    - name: Test Client Arguments
      run: |
      
        # Test: No arguments
        ./client || test $? -eq 1

        # Test: Invalid port (zero)
        ./client 127.0.0.1 0 || test $? -eq 1

        # Test: Invalid port (non-integer)
        ./client 127.0.0.1 -1234.5 || test $? -eq 1

    - name: Test Client and Server Interaction
      run: |
        # Start server in the background
        ./server 8080 & SERVER_PID=$!

        # Give the server time to start
        sleep 2

        # Test: Valid client-server interaction
        echo "Connecting to server at 127.0.0.1:8080" > EXPECTED_OUTPUT.txt
        echo "Enter the path to check (or 'exit' to quit):" >> EXPECTED_OUTPUT.txt
        echo "Server response: Free:" >> EXPECTED_OUTPUT.txt
        echo "Enter the path to check (or 'exit' to quit):" >> EXPECTED_OUTPUT.txt
        echo "Server response: Free:" >> EXPECTED_OUTPUT.txt
        echo "Enter the path to check (or 'exit' to quit):" >> EXPECTED_OUTPUT.txt
        echo "Server response: Error: " >> EXPECTED_OUTPUT.txt
        echo "Enter the path to check (or 'exit' to quit):" >> EXPECTED_OUTPUT.txt
        echo "Server response: Exiting." >> EXPECTED_OUTPUT.txt

        (
          echo "/"
          echo "/home"
          echo "/invalid"
          echo "exit"
        ) | ./client 127.0.0.1 8080 > ACTUAL_OUTPUT.txt

        # Compare the expected and actual output (allowing for dynamic parts)
        if ! diff -q EXPECTED_OUTPUT.txt ACTUAL_OUTPUT.txt; then
            echo "Test failed: Output mismatch"
            echo "Expected:"
            cat EXPECTED_OUTPUT.txt
            echo "Actual:"
            cat ACTUAL_OUTPUT.txt
            kill $SERVER_PID
            exit 1
        fi

        # Kill the server after the test
        kill $SERVER_PID


